steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/wideops-sasha/github.com/shoora-l/helloflask:$COMMIT_SHA'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  - push
  - gcr.io/wideops-sasha/github.com/shoora-l/helloflask:$COMMIT_SHA
  
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - cloudrunservice
  - --image
  - gcr.io/wideops-sasha/github.com/shoora-l/helloflask:$COMMIT_SHA
  - --region
  - us-central1
  - --platform
  - managed
  - --allow-unauthenticated


